
SET(SODIUM_SEARCH_PATHS
    /usr/local/
    /usr
    /opt
)

FIND_PATH(SODIUM_INCLUDE_DIR sodium/core.h 
    HINTS ${SODIUM_ROOT}
    PATH_SUFFIXES include
    PATHS ${SODIUM_SEARCH_PATHS}
)

FIND_LIBRARY(SODIUM_LIBRARY sodium
    HINTS ${SODIUM_ROOT}
    PATH_SUFFIXES lib64 lib bin
    PATHS ${SODIUM_SEARCH_PATHS}
)

IF(SODIUM_INCLUDE_DIR AND SODIUM_LIBRARY)
   SET(SODIUM_FOUND TRUE)
ENDIF()


IF(SODIUM_FOUND)
    MESSAGE(STATUS "Found libsodium: ${SODIUM_LIBRARY}")
ELSE()
    MESSAGE(WARNING "Could not find libsodium")
ENDIF()